// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NotificationFeedController from "./notification_feed_controller"
application.register("notification-feed", NotificationFeedController)

import RankSelectorController from "./rank_selector_controller"
application.register("rank-selector", RankSelectorController)

import RemovalsController from "./removals_controller"
application.register("removals", RemovalsController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)
